/**
 * AtmosFlow Data Center Demo Data
 * Showcases zone-specific scoring, gaseous corrosion, ISO particle counts,
 * AIHA worst-zone override, and mixed-use defensibility.
 */

export const DEMO_DC_PRESURVEY = {
  ps_assessor: 'R. Okonkwo, CIH',
  ps_assessor_certs: ['CIH', 'CHMM'],
  ps_assessor_exp: '10-20 years',
  ps_inst_iaq: 'TSI Q-Trak 7575',
  ps_inst_iaq_serial: 'QT-2025-14201',
  ps_inst_iaq_cal: '2026-03-01',
  ps_inst_iaq_cal_status: 'Calibrated within manufacturer spec',
  ps_reason: 'Routine / scheduled assessment',
}

export const DEMO_DC_BUILDING = {
  fn: 'Hizinburg Data Center — Building 2',
  fl: '8100 Gateway Blvd, Newark, NJ 07102',
  ft: 'Data Center',
  ba: '2012',
  ht: 'CRAC / Precision Cooling',
  hm: 'Within 6 months',
  fm: 'MERV 14',
  fc: 'Clean',
  sa: 'Yes — good airflow',
  od: 'Controlled',
}

export const DEMO_DC_ZONES = [
  {
    zn: 'Data Hall A — Primary',
    su: 'data_center',
    zone_subtype: 'data_hall',
    za: '12000',
    zo: '2',
    tf: '68',
    rh: '45',
    pm: '8',
    co2: '520',
    co2o: '410',
    meas_time: '10:30 AM',
    meas_occ: 'Typical occupancy',
    meas_duration: '15-minute average',
    gaseous_corrosion: 'G1 — Mild',
    dp_temp: '46',
    iso_class: 'ISO Class 7',
  },
  {
    zn: 'Data Hall B — Expansion',
    su: 'data_center',
    zone_subtype: 'data_hall',
    za: '8000',
    zo: '1',
    tf: '72',
    rh: '62',
    pm: '22',
    co2: '480',
    co2o: '410',
    meas_time: '11:15 AM',
    meas_occ: 'Below typical',
    meas_duration: '15-minute average',
    gaseous_corrosion: 'G3 — Harsh',
    dp_temp: '58',
    iso_class: 'ISO Class 8',
  },
  {
    zn: 'NOC Operations Center',
    su: 'office',
    zone_subtype: 'noc_office',
    za: '1800',
    zo: '8',
    cx: 'Yes — complaints reported',
    sy: ['Headache', 'Fatigue', 'Eye irritation'],
    sr: 'Yes — clear pattern',
    ac: '3-5',
    cc: 'Yes — this zone',
    tc: 'Too cold',
    hp: 'Too dry',
    tf: '66',
    rh: '28',
    co2: '890',
    co2o: '410',
    pm: '10',
    meas_time: '11:45 AM',
    meas_occ: 'Typical occupancy',
    meas_duration: '15-minute average',
  },
]
