/**
 * Prudence Safety & Environmental Consulting, LLC
 * Copyright (c) 2026 Prudence Safety & Environmental Consulting, LLC
 * All rights reserved.
 *
 * This software is the proprietary information of Prudence Safety
 * & Environmental Consulting, LLC. Unauthorized copying, modification,
 * distribution, or use is strictly prohibited.
 *
 * Contact: tsidi@prudenceehs.com
 */

export const DEMO_PRESURVEY = {
  ps_assessor: 'J. Smith, CIH, CSP',
  ps_assessor_certs: ['CIH', 'CSP', 'OSHA 30-Hour'],
  ps_assessor_exp: '10-20 years',
  ps_inst_iaq: 'TSI Q-Trak 7575',
  ps_inst_iaq_serial: 'QT-2024-08712',
  ps_inst_iaq_cal: '2026-01-15',
  ps_inst_iaq_cal_status: 'Calibrated within manufacturer spec',
  ps_inst_pid: 'RAE Systems MiniRAE 3000',
  ps_inst_pid_cal: 'Bump-tested and calibrated',
  ps_reason: 'Occupant complaint(s)',
  ps_complaint_narrative: 'Multiple occupants on the 3rd floor reported persistent headaches, fatigue, and eye irritation beginning approximately 3 weeks ago. Symptoms are reportedly worse in the afternoon and improve on weekends. Facility manager noted that HVAC maintenance was deferred due to budget constraints.',
  ps_complaint_severity: 'Significant — multiple occupants affected',
  ps_complaint_formal: 'Yes — to management / HR',
  ps_prior: 'Yes — with findings',
  ps_prior_notes: 'Previous assessment in 2024 identified ventilation deficiencies on floors 2-4. Recommendations for OA damper repair were partially implemented.',
  ps_blueprints: 'Yes — reviewed',
  ps_design_oa: 'Yes — documented CFM',
  ps_design_oa_cfm: '2400',
  ps_filter_schedule: 'Semi-annual',
  ps_water_history: 'Yes — recurring',
  ps_water_detail: 'Recurring roof leak above 3rd floor NE corner. Last repaired October 2025, reported leaking again February 2026.',
  ps_complaint_count: '12',
  ps_complaint_timeline: '1-6 months ago',
  ps_affected_areas: '3rd Floor — open office area, conference rooms B and C',
}

export const DEMO_BUILDING = {
  fn: 'Meridian Commerce Tower',
  fl: '450 Commerce Blvd, Suite 300, Hartford, CT 06103',
  ft: 'Commercial Office',
  ba: '1998',
  rn: 'Within 6 months',
  ht: 'Central AHU — VAV',
  hm: 'Over 12 months',
  fm: 'MERV 11',
  fc: 'Heavily loaded',
  sa: 'Weak / reduced',
  od: 'Closed / minimum',
  dp: 'Standing water',
  bld_pressure: 'Negative (air pulls in)',
  bld_exhaust: ['Restroom exhaust', 'Kitchen / break room hood'],
  bld_intake_proximity: ['Near parking garage', 'Near loading dock'],
  wx_temp: '72',
  wx_rh: '65',
  wx_sky: 'Overcast',
  wx_precip: 'Light rain within 24 hours',
  wx_wind: 'Light (5-15 mph)',
}

export const DEMO_ZONES = [
  {
    zn: '3rd Floor Open Office',
    su: 'office',
    sf: '4200',
    oc: '35',
    cx: 'Yes — complaints reported',
    sy: ['Headache', 'Fatigue', 'Eye irritation', 'Concentration issues', 'Nasal congestion'],
    sr: 'Yes — clear pattern',
    ac: '6-10',
    cc: 'Yes — this zone',
    tc: 'Slightly warm',
    hp: 'Too humid / stuffy',
    vd: 'Light surface dust',
    wd: 'Old staining',
    wl: ['Ceiling'],
    mi: 'Suspected discoloration',
    op: 'Moderate persistent',
    ot: ['Musty / Earthy'],
    src_adjacent: ['Copier / printer room', 'Restrooms'],
    src_internal: ['New furniture / carpet / paint'],
    path_pressure: 'Negative (draws in)',
    path_crosstalk: 'Odors migrating from adjacent space',
    path_crosstalk_source: 'Break room cooking odors entering through ceiling plenum',
    co2: '1180',
    co2o: '415',
    tf: '77',
    tfo: '72',
    rh: '62',
    rho: '65',
    pm: '28',
    pmo: '12',
    co: '2',
    tv: '680',
    tvo: '85',
    hc: '0.022',
    meas_time: '2:15 PM',
    meas_occ: 'Typical occupancy',
    meas_duration: '15-minute average',
    meas_conditions: 'Yes — normal operations',
    znt: 'Ceiling tiles show water staining in NE quadrant. Musty odor intensifies near exterior wall. Supply diffusers producing weak airflow. Occupants report symptoms worse after lunch.',
  },
  {
    zn: 'Conference Room B',
    su: 'conference',
    sf: '480',
    oc: '12',
    cx: 'Yes — complaints reported',
    sy: ['Headache', 'Fatigue', 'Concentration issues'],
    sr: 'Partially',
    ac: '3-5',
    cc: 'Yes — this zone',
    tc: 'Too hot',
    hp: 'Too humid / stuffy',
    vd: 'None',
    wd: 'Active leak',
    wl: ['Ceiling', 'Walls'],
    mi: 'Small (< 10 sq ft)',
    op: 'Moderate persistent',
    ot: ['Musty / Earthy'],
    src_adjacent: ['Restrooms'],
    src_internal: [],
    path_pressure: 'Negative (draws in)',
    path_crosstalk: 'None observed',
    co2: '1420',
    co2o: '415',
    tf: '79',
    rh: '68',
    pm: '18',
    co: '1',
    tv: '320',
    hc: '0.008',
    meas_time: '3:00 PM',
    meas_occ: 'Above typical (meeting/event)',
    meas_duration: '15-minute average',
    meas_conditions: 'No — doors/windows open',
    znt: 'Active water intrusion from roof leak visible in NE corner. Small area of mold growth on ceiling tile and upper wall. CO2 elevated significantly during occupied meeting — room lacks dedicated OA supply.',
  },
]
