/**
 * AtmosFlow DOCX Report — Core Sections
 * Cover, Transparency, Executive Summary, Scope, Building Context, Findings Dashboard
 */

import { Paragraph, TextRun, HeadingLevel, AlignmentType, SectionType, PageBreak, ImageRun, Table, TableRow, TableCell, WidthType, ShadingType, BorderStyle } from 'docx'
import { FONTS, COLORS, SEV_COLORS, scoreColor, riskLabel } from './styles'
import { buildTable, kvTable, borderlessLayoutTable, dataCell, headerCell } from './tables'
import { markdownToDocx } from './markdownToDocx'
import { base64ToUint8Array, inferImageType, isImageDataUrl } from './images'
import { inferCitationsFromContext, filterManifestByRegistration } from '../../engine/report/citation-tracker'
import { LETTER_BODY_PAGE } from './page-setup'

const p = (text, opts = {}) => new Paragraph({
  children: [new TextRun({ text, font: FONTS.body, size: opts.size || 22, color: opts.color || COLORS.body, bold: opts.bold, italics: opts.italics })],
  alignment: opts.align || AlignmentType.LEFT,
  spacing: { after: opts.after !== undefined ? opts.after : 120 },
  ...(opts.heading ? { heading: opts.heading } : {}),
})

const bullet = (text, opts = {}) => new Paragraph({
  children: [new TextRun({ text, font: FONTS.body, size: 20, color: opts.color || COLORS.sub })],
  bullet: { level: 0 },
  spacing: { after: 60 },
})

const numbered = (text, idx) => new Paragraph({
  children: [new TextRun({ text: `${idx + 1}. ${text}`, font: FONTS.body, size: 20, color: COLORS.sub })],
  spacing: { after: 60 },
})

/**
 * Hard "IH Review Required" banner for the AI-assisted narrative.
 *
 * Renders immediately before any AI-generated narrative block. Pale-red
 * shaded single-cell table with a 1.5pt critical-red border. Replaces
 * the prior soft italic disclaimer, which was rendered as light-gray
 * body text and did not read as a hard banner to a downstream reader.
 *
 * Addresses the "AI-generated narrative without an 'IH Review Required'
 * label" anti-pattern documented in CLAUDE.md.
 */
function aiReviewRequiredBanner() {
  const redBorder = { style: BorderStyle.SINGLE, size: 12, color: SEV_COLORS.critical }
  const BANNER_BG = 'FEE2E2'
  const BANNER_WIDTH_DXA = 9360
  return new Table({
    rows: [new TableRow({
      children: [new TableCell({
        children: [
          new Paragraph({
            children: [new TextRun({
              text: 'AI-ASSISTED NARRATIVE — IH REVIEW REQUIRED',
              font: FONTS.body, size: 22, bold: true, color: SEV_COLORS.critical,
            })],
            spacing: { after: 80 },
          }),
          new Paragraph({
            children: [new TextRun({
              text: 'This narrative was generated by an AI-assisted screening tool from deterministic scoring output. It must be reviewed and approved by a qualified industrial hygienist or licensed environmental professional before distribution to a client.',
              font: FONTS.body, size: 18, color: COLORS.body,
            })],
            spacing: { after: 0 },
          }),
        ],
        shading: { type: ShadingType.CLEAR, fill: BANNER_BG },
        borders: { top: redBorder, bottom: redBorder, left: redBorder, right: redBorder },
        margins: { top: 140, bottom: 140, left: 200, right: 200 },
        width: { size: BANNER_WIDTH_DXA, type: WidthType.DXA },
      })],
    })],
    width: { size: BANNER_WIDTH_DXA, type: WidthType.DXA },
    columnWidths: [BANNER_WIDTH_DXA],
  })
}

/**
 * Build a centered ImageRun-bearing paragraph for the firm logo /
 * PE seal. Sizes are inches × 9525 EMU/inch — docx package wants
 * EMUs. 240×72 logo (≈ 2.5 in × 0.75 in) reads as a header mark
 * without crowding the cover title. PE seal at 100×100 (~1 in × 1
 * in) sits as a small credential mark above the confidential
 * footer. Returns null on invalid input so the caller can
 * conditionally inject only when present.
 */
function brandedImageParagraph(dataUrl, widthPx, heightPx, after = 200) {
  if (!isImageDataUrl(dataUrl)) return null
  try {
    return new Paragraph({
      alignment: AlignmentType.CENTER,
      spacing: { after },
      children: [
        new ImageRun({
          data: base64ToUint8Array(dataUrl),
          transformation: { width: widthPx, height: heightPx },
          type: inferImageType(dataUrl),
        }),
      ],
    })
  } catch {
    // Defensive: corrupt data URL shouldn't sink the report. Fall
    // back to silently dropping the image — the assessor sees the
    // textual identity block below either way.
    return null
  }
}

export function buildCoverPage(ctx) {
  const children = []
  // Top spacing — tighter when a logo is present so the logo +
  // wordmark + title cluster reads as one block. Without a logo we
  // keep the existing generous top margin so the title still feels
  // anchored vertically.
  children.push(p('', { after: ctx.firmLogo ? 1200 : 2400 }))

  // Branded logo (optional). Sits above the firm name + address.
  const logoPara = brandedImageParagraph(ctx.firmLogo, 240, 80, 200)
  if (logoPara) children.push(logoPara)

  // Firm identity block — name, address, optional phone + license.
  children.push(p(ctx.firmName, { align: AlignmentType.CENTER, size: 24, bold: true, color: COLORS.text, after: 120 }))
  children.push(p(ctx.firmAddress, { align: AlignmentType.CENTER, size: 20, color: COLORS.sub, after: ctx.firmPhone || ctx.firmLicense ? 60 : 400 }))
  if (ctx.firmPhone) {
    children.push(p(ctx.firmPhone, { align: AlignmentType.CENTER, size: 20, color: COLORS.sub, after: ctx.firmLicense ? 60 : 400 }))
  }
  if (ctx.firmLicense) {
    children.push(p(ctx.firmLicense, { align: AlignmentType.CENTER, size: 18, color: COLORS.muted, after: 400 }))
  }

  // Title — the report's anchor visual.
  children.push(p('Indoor Air Quality', { align: AlignmentType.CENTER, size: 44, bold: true, color: COLORS.text, after: 40 }))
  children.push(p('Assessment Report', { align: AlignmentType.CENTER, size: 44, bold: true, color: COLORS.text, after: 400 }))

  // Site + assessment metadata.
  children.push(p(`Site: ${ctx.facilityName}`, { align: AlignmentType.CENTER, size: 22, color: COLORS.sub, after: 60 }))
  children.push(p(`Location: ${ctx.address}`, { align: AlignmentType.CENTER, size: 22, color: COLORS.sub, after: 60 }))
  children.push(p(`Assessment Date: ${ctx.assessDate}`, { align: AlignmentType.CENTER, size: 22, color: COLORS.sub, after: 60 }))
  children.push(p(`Report Date: ${ctx.reportDate}`, { align: AlignmentType.CENTER, size: 22, color: COLORS.sub, after: 60 }))
  children.push(p(`Assessor: ${ctx.assessor}`, { align: AlignmentType.CENTER, size: 22, color: COLORS.sub, after: 60 }))
  children.push(p(`Report ID: ${ctx.reportId}`, { align: AlignmentType.CENTER, size: 22, color: COLORS.sub, after: 60 }))
  children.push(p('Version: 1.0  |  Status: Draft — Pending Professional Review', { align: AlignmentType.CENTER, size: 20, color: COLORS.muted, after: 600 }))

  // Optional PE / CIH seal — small credential mark above the
  // confidential footer. The seal IS the professional accountability
  // signal on a consultant-grade deliverable; the existing
  // "Draft — Pending Professional Review" status above it
  // communicates that the seal is the IH's, not AtmosFlow's.
  const sealPara = brandedImageParagraph(ctx.peSeal, 100, 100, 200)
  if (sealPara) children.push(sealPara)

  children.push(p('CONFIDENTIAL — FOR CLIENT USE ONLY', { align: AlignmentType.CENTER, size: 18, bold: true, color: COLORS.muted, after: 0 }))

  return {
    // v2.5.1 — explicit Letter portrait + 1-inch margins so the cover
    // page renders at the same content width as the body section.
    properties: { page: LETTER_BODY_PAGE },
    children,
  }
}

export function buildExecutiveSummary(ctx) {
  const children = [
    p('Executive Summary', { heading: HeadingLevel.HEADING_2 }),
  ]

  if (ctx.comp) {
    // Score summary table
    children.push(buildTable(
      [{ text: 'Metric', width: 50 }, { text: 'Value', width: 50 }],
      [
        ['Composite score', { text: `${ctx.comp.tot}/100`, bold: true, color: scoreColor(ctx.comp.tot) }],
        ['Average zone score', `${ctx.comp.avg}/100`],
        ['Worst zone score', { text: `${ctx.comp.worst}/100`, color: scoreColor(ctx.comp.worst) }],
        ['Zones assessed', `${ctx.comp.count}`],
        ['Confidence', ctx.confidence],
      ]
    ))
    children.push(p('', { after: 120 }))
  }

  // Narrative
  if (ctx.narrative) {
    children.push(aiReviewRequiredBanner())
    children.push(p('', { after: 80 }))
    // Render the AI narrative's markdown (headings / bullets / tables)
    // into real docx blocks rather than a single flat paragraph.
    children.push(...markdownToDocx(ctx.narrative, { color: COLORS.sub }))
  } else if (ctx.comp) {
    const worst = ctx.zoneScores?.reduce((a, b) => a.tot < b.tot ? a : b, ctx.zoneScores[0])
    const worstCat = worst?.cats?.reduce((a, b) => (a.s / a.mx) < (b.s / b.mx) ? a : b)

    const hasGate5 = ctx.zoneScores?.some(zs => zs.cats?.some(c => c.gate5))
    const hasSynergistic = ctx.zoneScores?.some(zs => zs.cats?.some(c => c.synergistic))
    const criticalPrefix = hasGate5 ? 'Critical HVAC Condition Identified: Active moisture or filtration deficiency detected in HVAC system. ' : hasSynergistic ? 'Multiple Contaminant Exceedance: More than one Tier 1 contaminant exceeds OSHA Permissible Exposure Limits. Immediate follow-up sampling required. ' : ''

    const p1 = `${criticalPrefix}An indoor air quality assessment was conducted at ${ctx.facilityName} on ${ctx.assessDate}, encompassing ${ctx.zoneCount} zone${ctx.zoneCount !== 1 ? 's' : ''}${ctx.reason ? ` in response to ${ctx.reason.toLowerCase()}` : ''}. The assessment included direct-reading instrument measurements, visual inspection, HVAC system evaluation, and occupant complaint documentation.`

    const riskDesc = ctx.comp.tot >= 70
      ? 'Available evidence supports that conditions observed during the assessment window are broadly consistent with applicable occupancy standards, with localized areas warranting targeted follow-up as noted in the zone findings below.'
      : ctx.comp.tot >= 50
        ? `Conditions observed during the assessment window suggest moderate indoor air quality concerns. The composite score of ${ctx.comp.tot}/100 reflects a weighted evaluation across five categories, with ${worstCat ? `${worstCat.l} (${worstCat.s}/${worstCat.mx}) identified as the primary area of concern` : 'multiple categories showing room for improvement'}.`
        : `Conditions observed during the assessment window indicate significant indoor air quality concerns that would warrant prioritized remediation. The composite score of ${ctx.comp.tot}/100 reflects deficiencies across multiple evaluation categories${worstCat ? `, with ${worstCat.l} (${worstCat.s}/${worstCat.mx}) representing the most acute concern` : ''}.`

    const immRecs = ctx.recs?.imm || []
    const immText = (r) => (typeof r === 'string') ? r : (r?.text || '')
    const p3 = immRecs.length > 0
      ? `Priority actions include: ${immRecs.slice(0, 3).map(immText).join('; ')}. Additional engineering and administrative recommendations are detailed in the Recommendations Register.`
      : 'Recommended next steps are detailed in the Recommendations Register and Sampling Plan sections of this report.'

    children.push(p(p1, { size: 22, color: COLORS.sub }))
    children.push(p(riskDesc, { size: 22, color: COLORS.sub }))
    children.push(p(p3, { size: 22, color: COLORS.sub }))
  }

  // Priority actions — omit header entirely if no actions.
  // v2.8.0 — recs are RecommendationAction objects; render the
  // equipment label or zone name inline so the executive summary
  // table doesn't lose location context when scope is equipment.
  if (ctx.recs) {
    const rows = []
    const renderActionCell = (r) => {
      if (typeof r === 'string') return r
      if (!r) return ''
      if (r.scope === 'equipment') {
        const affects = r.affectedZoneNames?.length ? ` (Affects: ${r.affectedZoneNames.join(', ')})` : ''
        return `${r.equipmentLabel || r.equipmentId || 'Equipment'}: ${r.text}${affects}`
      }
      if (r.scope === 'zone') return `${r.zoneName || r.zoneId || ''}: ${r.text}`
      return r.text || ''
    }
    ;(ctx.recs.imm || []).forEach(r => rows.push([{ text: 'IMMEDIATE', bold: true, color: SEV_COLORS.critical, size: 18 }, renderActionCell(r)]))
    ;(ctx.recs.eng || []).slice(0, 3).forEach(r => rows.push([{ text: 'ENGINEERING', bold: true, color: COLORS.accent, size: 18 }, renderActionCell(r)]))
    ;(ctx.recs.adm || []).slice(0, 2).forEach(r => rows.push([{ text: 'ADMINISTRATIVE', bold: true, color: SEV_COLORS.medium, size: 18 }, renderActionCell(r)]))
    if (rows.length > 0) {
      children.push(p('Priority Actions', { heading: HeadingLevel.HEADING_3 }))
      children.push(buildTable([{ text: 'Priority', width: 20 }, { text: 'Action', width: 80 }], rows))
    }
  }

  return children
}
