/**
 * AtmosFlow free-tier watermark — docx-side implementation.
 *
 * The interface contract lives in src/engine/report/watermark.ts.
 * This module produces the actual docx Header / Footer / cover-page
 * paragraph objects and is imported by DocxReport.js to attach to
 * Section options.
 *
 * Spec:
 *   • Page header (every page): "GENERATED WITH ATMOSFLOW FREE TIER"
 *     in light gray (RGB 200,200,200), centered, 9pt
 *   • Page footer (every page): "Generated by AtmosFlow Free —
 *     atmosiq.prudenceehs.com — Upgrade for unrestricted reports"
 *   • Cover page closing line: "Free Tier Sample Report — for
 *     evaluation use only"
 *
 * Paid tier: all helpers return null / [] so the section options
 * carry no header/footer/notice.
 */

import { Header, Footer, Paragraph, TextRun, AlignmentType } from 'docx'

export const FREE_TIER_HEADER_TEXT = 'GENERATED WITH ATMOSFLOW FREE TIER'
export const FREE_TIER_FOOTER_TEXT = 'Generated by AtmosFlow Free — atmosiq.prudenceehs.com — Upgrade for unrestricted reports'
export const FREE_TIER_COVER_NOTICE = 'Free Tier Sample Report — for evaluation use only'

const HEADER_GRAY = 'C8C8C8' // RGB 200,200,200
const FOOTER_GRAY = '888888'

export function buildWatermarkHeader(watermarkConfig) {
  if (!watermarkConfig || watermarkConfig.tier !== 'free') return null
  return new Header({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            text: FREE_TIER_HEADER_TEXT,
            color: HEADER_GRAY,
            size: 18, // 9pt = 18 half-points
            font: 'Inter',
            bold: false,
          }),
        ],
      }),
    ],
  })
}

export function buildWatermarkFooter(watermarkConfig) {
  if (!watermarkConfig || watermarkConfig.tier !== 'free') return null
  const text = watermarkConfig.footerText || FREE_TIER_FOOTER_TEXT
  return new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            text,
            color: FOOTER_GRAY,
            size: 16, // 8pt
            font: 'Inter',
          }),
        ],
      }),
    ],
  })
}

export function buildCoverNoticeParagraph(watermarkConfig) {
  if (!watermarkConfig || watermarkConfig.tier !== 'free') return null
  return new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { before: 240, after: 0 },
    children: [
      new TextRun({
        text: FREE_TIER_COVER_NOTICE,
        color: FOOTER_GRAY,
        italics: true,
        size: 18,
        font: 'Inter',
      }),
    ],
  })
}

/**
 * Returns an object suitable for spreading into Section options:
 *   { headers: { default: ... }, footers: { default: ... } }
 * For paid tier, returns an empty object so the spread is a no-op.
 */
export function watermarkSectionAttachments(watermarkConfig) {
  if (!watermarkConfig || watermarkConfig.tier !== 'free') return {}
  return {
    headers: { default: buildWatermarkHeader(watermarkConfig) },
    footers: { default: buildWatermarkFooter(watermarkConfig) },
  }
}
