-- ═══════════════════════════════════════════════════════════════════
-- AtmosFlow — Supabase Database Schema (SUPERSEDED)
--
-- This file is no longer the source of truth and is NOT applied by the
-- migration runner. Its contents moved into the ledgered sequence under
-- supabase/migrations/ so a fresh database can be built end to end with
-- `npm run db:migrate` (see docs/DATABASE_MIGRATIONS.md):
--
--   • profiles table, RLS policies and the update_updated_at() helper
--       → 000_base_schema.sql
--   • assessments table (TEXT primary key — the uuid version that used
--     to live here conflicted with the ids the app mints)
--       → 014_assessments_table.sql
--
-- The `assessment-photos` storage bucket block that used to follow was
-- dropped: nothing in the app reads or writes that bucket (photos ride
-- inline in assessments.photos). Do not run this file by hand; add a
-- numbered migration instead.
-- ═══════════════════════════════════════════════════════════════════
