/**
 * Regression guard for the AI-narrative provenance banner.
 *
 * A red-bordered banner renders immediately BEFORE any AI-generated
 * narrative in the Executive Summary, and nothing renders when the prose
 * is deterministic output from scoring. Both behaviours are asserted so
 * the disclosure cannot silently regress.
 *
 * ── Why this survived the report-lifecycle refactor ────────────────────
 *
 * "IH Review Required" used to do two unrelated jobs: it labelled AI
 * prose (this banner) and it stamped every report as unfinished (the old
 * draft chrome). The lifecycle work removed the second — a screening
 * assessment is a finished document and now says so — and it would have
 * been easy to delete this in the same sweep.
 *
 * That would have been a real regression. This banner is a claim about
 * PROVENANCE: which sentences a machine wrote. A client-facing paragraph
 * generated by a model must stay distinguishable from one the assessor
 * wrote, in every lifecycle state. So the wording moved off "IH REVIEW
 * REQUIRED" — which read as a completeness verdict — while the
 * disclosure itself stayed.
 */
import { describe, it, expect } from 'vitest'
import { Table, Paragraph } from 'docx'
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — sections-core is a .js module without type declarations
import { buildExecutiveSummary } from '../../src/components/docx/sections-core'

function flatten(node: unknown): string {
  if (node == null) return ''
  if (typeof node === 'string') return node
  // docx TextRun stores its rendered text on the prototype-built tree.
  // The package builds an XML tree via .root[] arrays on each element;
  // for our purposes we just need to surface the visible text. The
  // user-facing string is stored as `text` on the TextRun's options,
  // which lands at `(node as any).options.text` or on the deeper tree.
  const anyNode = node as Record<string, unknown> & { root?: unknown[]; options?: Record<string, unknown> }
  let acc = ''
  if (anyNode.options && typeof anyNode.options.text === 'string') {
    acc += anyNode.options.text + ' '
  }
  if (Array.isArray(anyNode.root)) {
    for (const child of anyNode.root) acc += flatten(child)
  }
  return acc
}

describe('Executive Summary — AI narrative provenance banner', () => {
  it('renders a hard banner when ctx.narrative is present', () => {
    const ctx = {
      facilityName: 'Test Building',
      assessDate: '2026-05-19',
      zoneCount: 2,
      narrative: 'AI-assisted narrative body text describing the assessment.',
      comp: { tot: 72, avg: 72, worst: 65, count: 2 },
      confidence: 'medium',
      recs: { imm: [], eng: [], adm: [] },
    }

    const children = buildExecutiveSummary(ctx)
    const tables = children.filter((c: unknown) => c instanceof Table)

    // The banner is the only Table emitted before the narrative
    // paragraph; the score-summary table emitted earlier (when ctx.comp
    // is set) is also a Table. So locate the banner by its text.
    const banner = tables.find((t: unknown) => flatten(t).includes('VERIFY BEFORE ISSUE'))
    expect(banner, 'AI provenance banner not found in Executive Summary').toBeDefined()

    const bannerText = flatten(banner)
    expect(bannerText).toMatch(/AI-ASSISTED NARRATIVE/i)
    expect(bannerText).toMatch(/professional judgment/i)
    expect(bannerText).toMatch(/before issuing this report/i)
  })

  it('banner appears BEFORE the narrative paragraph in render order', () => {
    const ctx = {
      facilityName: 'Test Building',
      assessDate: '2026-05-19',
      zoneCount: 2,
      narrative: 'UNIQUE-NARRATIVE-MARKER-7F3A',
      comp: { tot: 72, avg: 72, worst: 65, count: 2 },
      confidence: 'medium',
      recs: { imm: [], eng: [], adm: [] },
    }

    const children = buildExecutiveSummary(ctx)
    const bannerIdx = children.findIndex((c: unknown) =>
      c instanceof Table && flatten(c).includes('VERIFY BEFORE ISSUE'))
    const narrativeIdx = children.findIndex((c: unknown) =>
      c instanceof Paragraph && flatten(c).includes('UNIQUE-NARRATIVE-MARKER-7F3A'))

    expect(bannerIdx).toBeGreaterThanOrEqual(0)
    expect(narrativeIdx).toBeGreaterThanOrEqual(0)
    expect(bannerIdx).toBeLessThan(narrativeIdx)
  })

  it('does NOT render the banner when ctx.narrative is absent (deterministic prose path)', () => {
    const ctx = {
      facilityName: 'Test Building',
      assessDate: '2026-05-19',
      zoneCount: 2,
      narrative: undefined,
      comp: { tot: 72, avg: 72, worst: 65, count: 2 },
      zoneScores: [
        { tot: 65, cats: [{ s: 12, mx: 25, l: 'Ventilation' }] },
      ],
      confidence: 'medium',
      recs: { imm: [], eng: [], adm: [] },
    }

    const children = buildExecutiveSummary(ctx)
    const tables = children.filter((c: unknown) => c instanceof Table)
    const banner = tables.find((t: unknown) => flatten(t).includes('VERIFY BEFORE ISSUE'))
    expect(banner, 'banner should not render for deterministic narrative path').toBeUndefined()
  })
})

describe('the banner is provenance, not a completeness verdict', () => {
  const ctx = {
    facilityName: 'Test Building',
    assessDate: '2026-05-19',
    zoneCount: 2,
    narrative: 'AI-assisted narrative body text.',
    comp: { tot: 72, avg: 72, worst: 65, count: 2 },
    confidence: 'medium',
    recs: { imm: [], eng: [], adm: [] },
  }

  it('no longer stamps the report as requiring review to be complete', () => {
    // The old wording read as "this document is unfinished", which is
    // exactly what the lifecycle refactor set out to stop saying.
    const text = buildExecutiveSummary(ctx).map(flatten).join(' ')
    expect(text).not.toMatch(/IH REVIEW REQUIRED/i)
    expect(text).not.toMatch(/pending (professional |IH )?review/i)
  })

  it('still discloses that a machine wrote the prose', () => {
    const text = buildExecutiveSummary(ctx).map(flatten).join(' ')
    expect(text).toMatch(/AI-ASSISTED NARRATIVE/i)
    expect(text).toMatch(/generated by an AI-assisted tool/i)
  })

  it('says the measurements and scores are not the AI-generated part', () => {
    // The distinction a reader needs: the numbers are deterministic;
    // only the wording around them came from a model.
    const text = buildExecutiveSummary(ctx).map(flatten).join(' ')
    expect(text).toMatch(/underlying measurements and scores are unaffected/i)
  })
})
