/**
 * Watermark configuration for AtmosFlow generated reports.
 *
 * Type-only module — no runtime engine logic, no scoring changes. The
 * docx renderer in src/components/docx/watermark.js implements the
 * actual paragraph/header/footer construction and references this
 * interface for shape consistency.
 *
 * Free-tier reports carry an upsell footer + page header watermark + a
 * cover-page notice. Paid reports render with no watermark and no
 * upsell language.
 */

export type WatermarkTier = 'free' | 'paid'

export interface WatermarkConfig {
  readonly tier: WatermarkTier
  /**
   * Optional override for the footer line. Defaults to the
   * canonical free-tier footer when tier is 'free' and to no footer
   * line when tier is 'paid'.
   */
  readonly footerText?: string
}

export const FREE_TIER_HEADER_TEXT = 'GENERATED WITH ATMOSFLOW FREE TIER'
export const FREE_TIER_FOOTER_TEXT = 'Generated by AtmosFlow Free — atmosiq.prudenceehs.com — Upgrade for unrestricted reports'
export const FREE_TIER_COVER_NOTICE = 'Free Tier Sample Report — for evaluation use only'

export function shouldWatermark(config: WatermarkConfig | null | undefined): boolean {
  return !!config && config.tier === 'free'
}
