/**
 * Prudence Safety & Environmental Consulting, LLC
 * Copyright (c) 2026 All rights reserved.
 *
 * LegalScreens — Terms of Service and Privacy Policy
 */

const BG = '#060609'
const CARD = '#101018'
const BORDER = '#1E1E2E'
const ACCENT = '#22D3EE'
const TEXT = '#F0F2F5'
const SUB = '#9BA4B5'
const DIM = '#6B7280'
const WARN = '#FBBF24'

function Section({ title, body, important }) {
  return (
    <div style={{
      padding: '18px 20px', background: important ? `${WARN}06` : CARD,
      border: `1px solid ${important ? `${WARN}30` : BORDER}`,
      borderRadius: 14, marginBottom: 10,
    }}>
      <div style={{ fontSize: 14, fontWeight: 700, color: TEXT, marginBottom: 8 }}>{title}</div>
      <div style={{ fontSize: 12, color: SUB, lineHeight: 1.7, whiteSpace: 'pre-line' }}>{body}</div>
    </div>
  )
}

export function TermsOfService({ onBack }) {
  return (
    <div style={{ paddingTop: 28, paddingBottom: 100 }}>
      <button onClick={onBack} style={{ background: 'none', border: 'none', color: ACCENT, fontSize: 15, fontWeight: 500, cursor: 'pointer', padding: '0 4px', marginBottom: 16, fontFamily: 'inherit' }}>← Settings</button>
      <div style={{ textAlign: 'center', marginBottom: 24 }}>
        <div style={{ fontSize: 12, fontWeight: 700, color: ACCENT, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 4 }}>AtmosFlow by Prudence EHS</div>
        <h2 style={{ fontSize: 24, fontWeight: 700, color: TEXT, margin: '0 0 4px' }}>Terms of Service</h2>
        <p style={{ fontSize: 12, color: DIM, margin: 0 }}>Effective Date: April 7, 2026</p>
      </div>

      <Section title="1. Acceptance of Terms" body='By accessing or using AtmosFlow (the "Platform"), operated by Prudence Safety & Environmental Consulting, LLC ("Prudence EHS"), you agree to be bound by these Terms of Service. If you do not agree, you may not use the Platform.' />
      <Section title="2. Description of Service" body="AtmosFlow is an AI-assisted indoor air quality assessment platform providing: building and zone-level air quality evaluations, contaminant scoring against OSHA PELs, ACGIH TLVs, and EPA guidelines, sampling plan generation, narrative report generation, and assessment history management." />
      <Section title="3. Advisory Nature — Critical Disclaimer" important body="ALL OUTPUTS GENERATED BY ATMOSFLOW ARE ADVISORY ONLY. The Platform does not guarantee regulatory compliance, does not constitute professional industrial hygiene advice, and is not a substitute for consultation with a qualified industrial hygienist, CIH, or environmental professional. Assessment scores are based on user-provided data — they do not represent certified measurements. Sampling plans are recommendations — they must be reviewed by a qualified professional before implementation. THE USER RETAINS SOLE RESPONSIBILITY for all workplace safety decisions and regulatory compliance." />
      <Section title="4. Intellectual Property" body="The Platform, including its source code, scoring algorithms, contaminant databases, AI prompt architecture, and user interface design, is the exclusive property of Prudence Safety & Environmental Consulting, LLC. You may not reverse engineer, decompile, scrape, or reproduce the Platform's methodology without written authorization." />
      <Section title="5. Payment Terms" body="AtmosFlow assessments are provided under the credit system. Pricing, credit packages, and free tier limits are displayed in the Platform. Payments are processed by Stripe. Credits are non-refundable once applied." />
      <Section title="6. User Responsibilities" body="You agree to: provide accurate assessment data; maintain account credential confidentiality; use the Platform only for lawful indoor air quality assessment purposes; review all AI outputs with professional judgment before acting; and not represent AI outputs as certified professional work unless reviewed by a qualified professional." />
      <Section title="7. Data Handling" body="Assessment data is stored securely in your account with row-level security. Documents and photos are processed and stored in encrypted cloud storage. Anonymous usage analytics are collected to improve the Platform (see Privacy Policy)." />
      <Section title="8. Limitation of Liability" important body="TO THE MAXIMUM EXTENT PERMITTED BY LAW, PRUDENCE EHS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, including regulatory citations, business losses, health impacts, or reliance on AI-generated recommendations. OUR TOTAL LIABILITY SHALL NOT EXCEED THE AMOUNT YOU PAID IN THE TWELVE (12) MONTHS PRECEDING THE CLAIM." />
      <Section title="9. Governing Law" body="These Terms are governed by the laws of the State of Maryland. Disputes shall be resolved through binding arbitration in Montgomery County, Maryland." />
      <Section title="10. Contact" body={"Prudence Safety & Environmental Consulting, LLC\nGermantown, MD\ninfo@prudencesafety.com"} />

      <div style={{ textAlign: 'center', padding: '16px 0 24px' }}>
        <div style={{ fontSize: 10, color: DIM }}>© 2026 Prudence Safety & Environmental Consulting, LLC</div>
      </div>
    </div>
  )
}

export function PrivacyPolicy({ onBack }) {
  return (
    <div style={{ paddingTop: 28, paddingBottom: 100 }}>
      <button onClick={onBack} style={{ background: 'none', border: 'none', color: ACCENT, fontSize: 15, fontWeight: 500, cursor: 'pointer', padding: '0 4px', marginBottom: 16, fontFamily: 'inherit' }}>← Settings</button>
      <div style={{ textAlign: 'center', marginBottom: 24 }}>
        <div style={{ fontSize: 12, fontWeight: 700, color: ACCENT, letterSpacing: 1, textTransform: 'uppercase', marginBottom: 4 }}>AtmosFlow by Prudence EHS</div>
        <h2 style={{ fontSize: 24, fontWeight: 700, color: TEXT, margin: '0 0 4px' }}>Privacy Policy</h2>
        <p style={{ fontSize: 12, color: DIM, margin: 0 }}>Effective Date: April 7, 2026</p>
      </div>

      <Section title="1. Information We Collect" body={"Account Information: When you create an account, we collect your email address. Your profile (name, certifications, instruments) is stored in your account.\n\nAssessment Data: Building details, zone measurements, contaminant levels, photos, and scoring results are stored in your account.\n\nUsage Data: We collect anonymous usage events (features used, assessment completion rates) to improve AtmosFlow. No personally identifiable information is included in usage events."} />
      <Section title="2. How We Use Your Data" body={"We use your data to:\n• Deliver air quality assessment results and reports\n• Save your assessment history and drafts\n• Improve the platform based on anonymous usage patterns\n• Process payments for assessment credits"} />
      <Section title="3. Analytics" body={"AtmosFlow uses lightweight, first-party analytics stored in our own database. We do NOT use Google Analytics, tracking pixels, cookies, browser fingerprinting, or any third-party analytics service.\n\nWhat we track: Feature usage, assessment completion rates, and score distributions. All analytics events are anonymous — they include a random session ID that resets when you close the app.\n\nYou can request that we stop collecting usage data by emailing info@prudencesafety.com."} />
      <Section title="4. Third-Party Services" body={"AtmosFlow integrates with:\n\n• Anthropic (Claude API): Assessment data may be sent for AI-powered narrative generation. Anthropic's commercial API does not use your data for model training.\n• Stripe: Payment processing. We do not store credit card details.\n• Supabase: Database and authentication provider. Data stored with row-level security."} />
      <Section title="5. Data Retention & Deletion" body={"Your account data and assessment history are retained until you request deletion. Analytics events are stored indefinitely in anonymized form.\n\nTo request deletion, email info@prudencesafety.com. Deletion requests are processed within 30 days."} />
      <Section title="6. Your Rights" body={"You have the right to:\n• Request a copy of all data associated with your account\n• Request deletion of your account and all stored data\n• Opt out of anonymous usage analytics\n• Export your data at any time via Settings → Export Backup"} />
      <Section title="7. Data Security" body={"We protect your data using:\n• Row-level security (users can only access their own data)\n• Encrypted connections (HTTPS/TLS) for all transmissions\n• Bearer token authentication\n• Offline-first architecture with encrypted local storage"} />
      <Section title="8. Children's Privacy" body="AtmosFlow is designed for industrial hygiene and environmental professionals and is not intended for use by individuals under 18." />
      <Section title="9. Changes to This Policy" body="We may update this Privacy Policy from time to time. Material changes will be communicated through the Platform. Continued use constitutes acceptance." />
      <Section title="10. Contact" body={"Prudence Safety & Environmental Consulting, LLC\nGermantown, MD\ninfo@prudencesafety.com"} />

      <div style={{ textAlign: 'center', padding: '16px 0 24px' }}>
        <div style={{ fontSize: 10, color: DIM }}>© 2026 Prudence Safety & Environmental Consulting, LLC</div>
      </div>
    </div>
  )
}
